### ISSUE TITLE
Add a way to kill a benchmark after X second/minutes/hours/...

### ISSUE THREAD

**Issue by guilhermeleobas** [sharkdp/hyperfine#106]
Hi @sharkdp,

I am using hyperfine to benchmark some a few long-running programs and I expect them to finish in a certain time. I would be good if hyperfine had the ability to kill the program after a certain time. Something similar to what [gnu-timeout](https://www.gnu.org/software/coreutils/manual/html_node/timeout-invocation.html#timeout-invocation) does. What do you think?

Regards

**Comment by sharkdp** [comment]
So I guess the whole benchmark should fail whenever the timeout triggers. Otherwise you would get a spoiled benchmark result.

So couldn't you just wrap your command with GNU timeout?

```
▶ hyperfine 'timeout 2 sleep 0.5'
Benchmark #1: timeout 2 sleep 0.5
  Time (mean ± σ):     507.0 ms ±   2.6 ms    [User: 5.7 ms, System: 1.2 ms]
  Range (min … max):   501.5 ms … 509.8 ms
 

/tmp                                                                                         
▶ hyperfine 'timeout 2 sleep 3'  
Benchmark #1: timeout 2 sleep 3
Error: Command terminated with non-zero exit code. Use the '-i'/'--ignore-failure' option if you want to ignore this. Alternatively, use the '--show-output' option to debug what went wrong.
```

**Comment by sharkdp** [comment]
I don't really see the point, to be honest. What would be the benefit of adding this to hyperfine?

**Comment by guilhermeleobas** [comment]
Well, It was just that instead of combining `timeout` and `hyperfine`, the later would have the functionalities from the former built in. One less dependency to take care of.

**Comment by sharkdp** [comment]
I think I'd rather not add this to hyperfine.

Running benchmarks with a timeout, in my opinion, is a very rare use case. It means that you are benchmarking a program which could take an *unexpectedly* long time, implying that the program behavior is not deterministic. Whenever the program *does* run into a timeout, you basically have to throw away the whole benchmark because you don't know how long that run would have taken.

**Comment by NathanBaulch** [comment]
FWIW, I needed this precisely because the programs I'm benchmarking are not deterministic - a coding challenge with submissions in different languages from developers with varying degrees of experience!

I went with GNU timeout as suggested above, wrapped in a sub-shell for composite commands.
eg, `hyperfine "timeout 2m sh -c 'python ./generate_graph.py && python ./five_clique.py'"`
