### ISSUE TITLE
Calculates whether the distributions of two benchmarks are different

### ISSUE THREAD

**Issue by uetchy** [sharkdp/hyperfine#217]
Suppose we have 2 benchmarks of the same functionality in different implementations and want to know whether these distributions are differed or statistically the same.

Possible solution:

### Welch's t-test

Here is the TypeScript reference implementation that consumes the JSON output of hyperfine and calculates the probability.

```js
import * as fs from 'fs';

const sum = (x: number[]) => x.reduce((a: number, b: number) => a + b);
const sqsum = (x: number[], mu: number) =>
  x.reduce((a: number, b: number) => a + (b - mu) ** 2);
const cdf = (x: number, c: number) => Math.exp(-(x ** -c));

function ttest(X: number[], Y: number[]) {
  const Xn = X.length;
  const Yn = Y.length;
  const X_mu = sum(X) / Xn;
  const Y_mu = sum(Y) / Yn;
  const X_sigma = sqsum(X, X_mu) / (Xn - 1);
  const Y_sigma = sqsum(Y, Y_mu) / (Yn - 1);
  const t = (X_mu - Y_mu) / Math.sqrt(X_sigma / Xn + Y_sigma / Yn);
  console.log(t);

  return cdf(-Math.abs(t), Xn + Yn - 2) * 2.0;
}

const result = JSON.parse(fs.readFileSync('./hyperfine.json').toString());
const X = result.results[0].times;
const Y = result.results[1].times;
const p = ttest(X, Y);
console.log(p < 0.05);
```

**Comment by sharkdp** [comment]
Thank you very much for your contribution. 

I'd be happy to add a script like this to the `scripts` folder in this repository, but it would be great if it could be ported to Python. This would be more in line with the available scripts and would probably make for a much simple script because we could use [`scipy.stats.ttest_ind`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html)

**Comment by uetchy** [comment]
Just noticed that `scripts` folder! It's reasonable to have this as a supplemental script.
I'll send a PR later to add Python script for T testing benchmarks.
