### ISSUE TITLE
Shell aliases and functions?

### ISSUE THREAD

**Issue by for-coursera** [sharkdp/hyperfine#270]
It can't test shell aliases and function, can it? :)

**Comment by sharkdp** [comment]
### `bash`

Bash functions can easily be benchmarked by exporting them:
```bash
$ sleep1() { sleep 1; }
$ export -f sleep1
$ hyperfine sleep1
Benchmark #1: sleep1
  Time (mean ± σ):      1.005 s ±  0.003 s    [User: 3.4 ms, System: 1.7 ms]
  Range (min … max):    1.001 s …  1.009 s    10 runs
```

As for `alias`es, I don't think there is a way to `export` them. But you can always put the alias or shell function into a separate file:
```bash
echo 'alias my_alias="sleep 1"' > /tmp/my_alias.sh
hyperfine 'source /tmp/my_alias.sh; eval my_alias'
```
Note that this needs to be an absolute path and that you have to use `eval` to expand `my_alias` only after `my_alias.sh` has been parsed.

### `zsh`

In `zsh`, exporting functions is not supported (by design). You would have to put the function or alias in a file as well:
```zsh
echo 'my_function() { sleep 1 }' > my_function.zsh
hyperfine --shell zsh 'source my_function.zsh; eval my_function'
```

**Comment by for-coursera** [comment]
Thanks! (I'm not closing this since you mentioned probably adding these hints to the documentation but feel free to close if needed.)
