### ISSUE TITLE
Feature request: Option to use as a simple command timer?

### ISSUE THREAD

**Issue by michaelmoussa** [sharkdp/hyperfine#276]
My first thought upon discovering this great utility was to do `alias time="hyperfine --runs 1"` and use it whenever I'd normally use the `time` command as well. That, understandably, isn't allowed due to needing two or more runs to compute variance, but I still want to do it! :)

Would you merge a PR that adds something along the lines of the following?

```bash
    -t, --time
        Perform a single run and display its timing, omitting any
        extended statistics. Implies "--runs 1" and "--show-output"
```

I realize this is probably an edge case and _not_ the primary intent of this utility, but I figured I'd ask since it doesn't seem like too much of a stretch. Regardless, thanks for your work on this!

**Comment by sharkdp** [comment]
Thank you very much for your feedback!

That sounds like a reasonable request, but what exactly would be the benefit over using `time`?

We would have to omit almost every field from the output:
![image](https://user-images.githubusercontent.com/4209276/78038299-fad2c280-736c-11ea-8744-b6de4b190ac1.png)

* All of "sigma", "min", "max" and "# runs" would be useless
* I guess we could still call it "mean", but it would be misleading
* "User" and "System" are still fine.

**Comment by michaelmoussa** [comment]
The benefits are admittedly *very* minor, so hopefully the level of effort to implement would be the same.

* Millisecond display by default vs. `time` that always uses seconds.
* Colorized output of `hyperfine` is much easier to read at a glance. If I needed to, I'd probably `alias time="hyperfine --runs 2"` just for that.
* I use `time` for individual time checks much more often than I do any kind of benchmarking. Being able to use hyperfine for individual command timing as well guarantees that I'll remember to use it the next time I need to benchmark, versus scrolling through my GitHub stars thinking "hmm... what was that cool command benchmark tool I saw recently called again?"

re: omitting fields, I don't think that'd be strictly necessary. The default behavior of automatically determining a number of runs to use would be unchanged. Explicitly using the `--time` flag means the user is intentionally limiting it to only one run. Yes, a single run *does* make the `min`, `max`, `# runs`, and `mean` values useless, it *doesn't* make them objectively wrong, and the person using it shouldn't be surprised that `min = max = mean` and that the variance is 0.

**Comment by sharkdp** [comment]
Ok, if we can leave the default layout the same and just output the values as is (even if meaningless), I'm fine with this change.

We could even think about hiding this feature from the `--help` text (it could still be documented in the man page) in order not to confuse the "average user".

Concerning colors, notice that the colorized output is disabled when using `--show-output`. We have also marked `--style` and `--show-output` as "conflicting", which means that you can not use `--style` to force colored output. I think that's actually overly restrictive. What we originally wanted (if I remember correctly) was to disable the interactive components (the progress bar and spinner). Colorized output (`--style=color` instead of `--style=full`) should be fine. Maybe we can change that.

**Comment by michaelmoussa** [comment]
Sounds good! I think I can handle implementing this (as well as the colorized output portion), so I'll submit a PR sometime this week.

**Comment by sharkdp** [comment]
Closing this for now, unless there is further feedback.

**Comment by sharkdp** [comment]
@michaelmoussa This is now supported via #447.
