### ISSUE TITLE
Provide shell completions at runtime

### ISSUE THREAD

**Issue by shilangyu** [sharkdp/hyperfine#293]
I saw the addition of shell completions (#290) to release artifacts however I personally am a proponent of providing them also/instead at runtime as a command.

**An example:**
[Deno](https://github.com/denoland/deno) provides a subcommand to generate them. Example: `deno completions fish > /my/fish/dir/deno.fish`

This way I can generate them any time I want (or when I update hyperfine) and decide for myself where to put them. Looking for the completion files in the released artifacts is often cumbersome.

Clap makes this trivial so I can send a PR if this idea sounds good.

**Comment by sharkdp** [comment]
I'm not really convinced. I think this something which should rather be left to package managers to handle correctly upon installation/updating.

If you are really installing by downloading the release tarballs, it shouldn't be hard to copy the completion files anywhere you want (instead of looking up how to generate them at runtime).

> This way I can generate them any time I want (or when I update hyperfine)

Why would you generate them at any other time except for when hyperfine is updated to a new version?


That being said… if this is a small change to the codebase and if we hide this new command line option from the `--help` text, I'm okay with in icluding this.
