### ISSUE TITLE
Divide by zero and other issues when detecting outliers

### ISSUE THREAD

**Issue by tdulcet** [sharkdp/hyperfine#329]
When calculating the modified Z-scores, if many of the times are the same, the MAD will be zero (see [here](https://stats.stackexchange.com/q/339932)), which means this line will divide by zero: https://github.com/sharkdp/hyperfine/blob/7cdd1f259f607388efb03d980ef41ccd8f0e78a6/src/hyperfine/outlier_detection.rs#L33
The above link has a simple example that you can add to your test suit to reproduce this issue.

---

Additionally, the test suite correctly takes the absolute value of the modified Z-scores: https://github.com/sharkdp/hyperfine/blob/7cdd1f259f607388efb03d980ef41ccd8f0e78a6/src/hyperfine/outlier_detection.rs#L47
However, the program does not: https://github.com/sharkdp/hyperfine/blob/84f3120949f3538c84845389e6e0e248fff15fb9/src/hyperfine/benchmark.rs#L397-L400
Which means that it is missing 50% of the outliers.

I found these issues while testing hyperfine and implementing [my Bash port](https://github.com/tdulcet/Benchmarking-Tool). Thank you for making this wonderful tool!

**Comment by sharkdp** [comment]
Thank you very much for your feedback and for this detailed bug report!

> which means this line will divide by zero

I guess this could be related to #319 as well, but I did not take a closer look yet. Definitely looks like a problem.

>  […] However, the program does not […] Which means that it is missing 50% of the outliers.

Oh that is bad. The comment of the `modified_zscores` function also seems wrong because it includes the absolute value ("whereas the modified Z-score is defined by `|x_i - x_median|/MAD`"), which would mean that everything is fine. But the implementation returns (x_i - x_median) / MAD.

How could this have gone unnoticed for so long :-/.

**Comment by sharkdp** [comment]
Fixed in [hyperfine v1.11.0](https://github.com/sharkdp/hyperfine/releases/tag/v1.11.0).
