### ISSUE TITLE
question:     Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.

### ISSUE THREAD

**Issue by monacv** [sharkdp/hyperfine#355]
Hello,

Do you expect this warning?
```

[22892:3298 0:1114] 04:34:49 Tue Dec 29 [mona@goku:pts/3 +1] ~
$ hyperfine 'sleep 0.3'
Benchmark #1: sleep 0.3
  Time (mean ± σ):     303.1 ms ±   0.9 ms    [User: 1.9 ms, System: 0.7 ms]
  Range (min … max):   301.3 ms … 303.8 ms    10 runs
 
  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.

```

**Comment by sharkdp** [comment]
> Do you expect this warning?

That's certainly possible if your system is otherwise busy. I can reproduce this by running
```
timeout 0.4s stress --cpu 8 --io 8
```
in the background while performing the `hyperfine 'sleep 0.3'` benchmark.

Have you tried what is suggested in the warning?

> Consider re-running this benchmark on a quiet PC without any interferences from other programs.

Now obviously, it's not possible to shut down *every* other program. But things like a browser, Dropbox, Spotify, etc. should definitely be shut down before running a serious benchmark.
