### ISSUE TITLE
standard error

### ISSUE THREAD

**Issue by JuliaLawall** [sharkdp/hyperfine#417]
I would like to use the results of hyperfine to make a graph with error bars.  What formula is hyperfine using to compute the standard deviation?  Is it the sample standard deviation, meaning that the result should be divided by the square root of the number of samples to obtain the standard error for the error bars?

**Comment by sharkdp** [comment]
>  What formula is hyperfine using to compute the standard deviation? Is it the sample standard deviation

Yes. It's the square root of the sample variance, i.e. with the *1/(N-1)* prefactor.

> meaning that the result should be divided by the square root of the number of samples to obtain the standard error for the error bars?

Yes. If you want to show the standard error as error-bars, that is correct.

For the plot-scripts that come with `hyperfine`, we directly show the standard-deviation as the error bars:

https://github.com/sharkdp/hyperfine/blob/34558bf141132f2aa94a3ab851185ee142e611bd/scripts/plot_parametrized.py#L90

This allows us to show the typical spread of runtimes (instead of the accuracy of the mean runtime). Both methods are fine. It depends on what you want to show.

**Comment by JuliaLawall** [comment]
On Mon, 16 Aug 2021, David Peter wrote:

>
>       What formula is hyperfine using to compute the standard
>       deviation? Is it the sample standard deviation
>
> Yes. It's the square root of the sample variance, i.e. with the 1/(N-1)
> prefactor.
>
>       meaning that the result should be divided by the square root of
>       the number of samples to obtain the standard error for the error
>       bars?
>
> Yes. If you want to show the standard error as error-bars, that is correct.
>
> For the plot-scripts that come with hyperfine, we directly show the
> standard-deviation as the error bars:
>
> https://github.com/sharkdp/hyperfine/blob/34558bf141132f2aa94a3ab851185ee14
> 2e611bd/scripts/plot_parametrized.py#L90
>
> This allows us to show the typical spread of runtimes (instead of the
> accuracy of the mean runtime). Both methods are fine. It depends on what you
> want to show.

Thanks!
