### ISSUE TITLE
Auto warm-up

### ISSUE THREAD

**Issue by ole-tange** [sharkdp/hyperfine#451]
If the command requires warm up it will usually be slower before warm up.

I propose automatically detecting this:

~~~
runtime = run(job)
do
  last_runtime = runtime
  runtime = run(job)
while last_runtime > runtime
# Use both last_runtime and runtime as part of measurements
~~~

So only start measuring when the runtime has reached a low.

**Comment by sharkdp** [comment]
> If the command requires warm up it will usually be slower before warm up.
> 
> I propose automatically detecting this:

hyperfine already does this:

```
▶ hyperfine 'fd'                                                          
Benchmark 1: fd
  Time (mean ± σ):     253.0 ms ± 119.4 ms    [User: 870.8 ms, System: 738.3 ms]
  Range (min … max):   207.5 ms … 592.6 ms    10 runs
 
  Warning: The first benchmarking run for this command was significantly slower
  than the rest (592.6 ms). This could be caused by (filesystem) caches that were
  not filled until after the first run. You should consider using the '--warmup'
  option to fill those caches before the actual benchmark. Alternatively, use the
  '--prepare' option to clear the caches before each timing run.
```



> So only start measuring when the runtime has reached a low.

Interesting idea. But the proposed procedure would introduce a statistical bias in the measurements. If we only start measuring when the runtime *goes up*, the first two measurement times T_1, T_2 would always satisfy T_1 < T_2 and would not be statistically independent.

There's probably a way to compute this analytically, but for now, let's just run a simulation:
```python
import numpy as np


def fake_runtime():
    return np.random.normal(loc=10.0, scale=1.0)


def measure_mean_runtime():
    last_runtime = fake_runtime()
    runtime = fake_runtime()
    while last_runtime > runtime:
        last_runtime = runtime
        runtime = fake_runtime()

    measurements = [last_runtime, runtime]

    # do three more normal benchmark runs
    for i in range(3):
        measurements.append(fake_runtime())

    return np.mean(measurements)


mean_runtimes = []
for _ in range(1_000_000):
    mean_runtimes.append(measure_mean_runtime())

print(np.mean(mean_runtimes))
```

This outputs 9.9468 ± 0.0002 instead of the expected 10,0 mean runtime. Sure, the error is small (0.053 σ), but that's not something I would like to introduce.

**Comment by ole-tange** [comment]
If you want to avoid this, simply ignore [last_runtime, runtime].
