### ISSUE TITLE
Prebuilt binaries require very recent glibc (2.29 released 2019-01)

### ISSUE THREAD

**Issue by haampie** [sharkdp/hyperfine#508]
Starting from hyperfine 1.13.0, there's suddenly a dependency on:
```
w statx@GLIBC_2.28
w posix_spawn_file_actions_addchdir_np@GLIBC_2.29
```

which is a very recent glibc version from 2019.

Can you relax that requirement? ~Or possibly statically link musl libc?~ I missed that the musl libc version is statically linked.

Version 1.12.0 used to only require glibc 2.18 (released 2013-08)

**Comment by sharkdp** [comment]
Thank you for reporting this.

That could be due to the [Ubuntu 18.04 => 20.04 change in our CI runners](https://github.com/sharkdp/hyperfine/commit/a5cac67ee685949a19194850185a25a7439f5c1b). I had a similar problem in another project of mine which we actually solved by "cross"-compiling using https://github.com/cross-rs/cross, because their Docker images use quite old versions of libc (maybe on purpose?): 2.15 for x86_64-unknown-linux-gnu (https://github.com/cross-rs/cross#supported-targets)

**Comment by plutonium-239** [comment]
Hey @sharkdp how can I check what is the last version using `<= GLIBC 2.17` (I am on an HPC system running CentOS7 and they are not going to update `glibc` from `2.17` in CentOS7).
I checked the last 2 versions but was getting the same error.

**Comment by sharkdp** [comment]
I'm not sure I understand what you are asking

**Comment by plutonium-239** [comment]
I was asking which is the last hyperfine version using `GLIBC` of version below `2.17`, as I cannot update my `GLIBC`. 
I had solved it by installing via `conda`.

**Comment by sharkdp** [comment]
I don't know, sorry. You would have to download all and find out somehow (I think you can use some combination of `strings <binary>` and `grep -i glibc` to get an idea.. but it's not a foolproof method, I guess. I don't know a better way).
