### ISSUE TITLE
Support changing the default of "it will measure for at least 3 seconds"

### ISSUE THREAD

**Issue by RalfJung** [sharkdp/hyperfine#527]
It would be nice if one could change the default of "it will measure for at least 3 seconds"; e.g. I might be fine with 30s of measurement for tests that usually take around 2-5s. Being able to specify the time rather than having to use `-m` is nice because my level of patience to wait for results is mostly constant, so I am fine with more runs when the individual runs are faster.

Looks like this is where the time is currently hard-coded:
https://github.com/sharkdp/hyperfine/blob/3df63ba2bb14e75775e0e1fae744043e7ad79a5f/src/options.rs#L208

**Comment by sharkdp** [comment]
Thank you for your feedback.

I certainly agree that having a hardcoded default is not the best option here. However, I would like to avoid having multiple (conflicting) command-line options to control the number of runs. Mostly because I think it would be difficult to explain to users.

So my question is: what would be possible alternatives to the introduction of a new `--min-benchmarking-time <secs>` option? For example, is the "min. benchmarking time" strategy reasonable at all? Maybe something like a confidence-based min. benchmarking time would be more suitable?

Contrarily, are there other use cases for the suggested option? Maybe someone is aware of background interference of the benchmarks on a timescale of e.g. a few minutes and would therefore like to set `--min-benchmarking-time=10min`.

**Comment by sharkdp** [comment]
Given how easy this should be to implement, I'm inclined to just add this as a new option, but maybe mark it "hidden" for now... until we are sure that we like the "CLI design". This would hide the option from the `--help` text but still make it usable. An experimental feature, if you will.

**Comment by udsamani** [comment]
@sharkdp Are we looking to add this (by default hidden)? Would like to take a stab at it if you don't mind !

**Comment by sharkdp** [comment]
That would be great!

**Comment by udsamani** [comment]
@sharkdp Just confirming are we planning to go with confidence based benchmarking or just introduce a parameter for existing but just keep it hidden ?

**Comment by sharkdp** [comment]
> @sharkdp Just confirming are we planning to go with confidence based benchmarking or just introduce a parameter for existing but just keep it hidden ?

Both :smile:

**Comment by sharkdp** [comment]
@udsamani Sorry that I jumped in here, but I wanted to include that in the release I made yesterday. There are a lot of other issues on this tracker if you want to work on hyperfine!
