### ISSUE TITLE
Can't install hyperfine latest version on MacbookPro - Apple M1 Pro | brew

### ISSUE THREAD

**Issue by saritvakrat** [sharkdp/hyperfine#610]
System info:
 System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    npm: 9.2.0 - /usr/local/bin/npm

When trying to install using brew:
Error: hyperfine: Failed to download resource "hyperfine_bottle_manifest"
Download failed: https://ghcr.io/v2/homebrew/core/hyperfine/manifests/1.15.0

Can't install also using npm

**Comment by sharkdp** [comment]
hyperfine is not available via npm. Please see https://github.com/sharkdp/hyperfine#installation for installation options.

**Comment by saritvakrat** [comment]
@sharkdp  I installed using brew not npm

**Comment by sharkdp** [comment]
Can you please report this with homebrew? Or do you think it is related to something inside this repo (hyperfine itself)?

**Comment by saritvakrat** [comment]
Since i tried installing directly and in homebrew and failed in both, seems like an issue with hyperfine

**Comment by sharkdp** [comment]
I guess it's related to your CPU architecture (Apple M1 Pro). We don't have any suitable binary for it.

**Comment by 0mp** [comment]
I installed `hyperfine` 1.15.0 today with `brew install hyperfine` on Apple M1, macOS Ventura 13.2.1.

**Comment by sharkdp** [comment]
@0mp Any ideas as to what have gone wrong in @saritvakrat​s setup? I don't have a Mac, so I can't really help here.

**Comment by 0mp** [comment]
@saritvakrat what's the error you are getting from `npm`?

**Comment by sharkdp** [comment]
Brew, not npm

**Comment by 0mp** [comment]
Yes, but the OP mentioned `npm` so I was curious if that's related.

Anyhow, as I said, `hyperfine` installs just fine on M1 with `brew`. It's Homebrew formula is also rather simple: https://github.com/Homebrew/homebrew-core/blob/master/Formula/hyperfine.rb so I doubt it's a bug in the formula itself. I'd say that this is not a problem that can be fixed by the Hyperfine project. The bug report should be sent to the Homebrew project. :(

**Comment by sharkdp** [comment]
Ok, thanks.
