### ISSUE TITLE
Add nushell completions

### ISSUE THREAD

**Issue by j-xella** [sharkdp/hyperfine#764]
hyperfine comes with completions files for bash, zsh, fish, powershell ....

Can nushell have some love too?

**Comment by sharkdp** [comment]
It does not seem to be supported by clap_complete at the moment: https://docs.rs/clap_complete/latest/clap_complete/aot/enum.Shell.html

Closing this for now (until upstream supports this potentially)

**Comment by RGBCube** [comment]
There exists a clap_complete_nushell crate that's in the clap repo and cratesio that provides this functionaly.

The reason why it isn't in the main crate seems to be because Nushell isn't stable yet, but the stuff generated by it won't be changed any time soon.

Could that crate be integrated into the build.rs?

**Comment by sharkdp** [comment]
> Could that crate be integrated into the build.rs?

Sure.
