### ISSUE TITLE
Add option to choose the units used for CLI & results output

### ISSUE THREAD

**Issue by jasonpeacock** [sharkdp/hyperfine#80]
(a follow up to #71)

Currently the CLI automatically selects the units (seconds, milliseconds) based on the size of the `mean` value, but the results export is always in seconds.

Choosing the units will force for the CLI and results export units to always match, and allow users to specify the units they are most familiar with/integrate with their reporting systems.

The option could be `-u --units <Seconds|Milliseconds>`, and maybe extended to also include minutes (and hours)?

---

The units option value would be passed through to both `format::format_duration_units` for the CLI and `ExportManager::write_results` for the results export.

**Comment by sharkdp** [comment]
Thank you for the feedback!

If this only affects the CLI and the Markdown export, this sounds good to me.

I'd suggest `-u --time-unit <millisecond|second|...>`.

**Comment by Kaos-Industries** [comment]
I would also look forward to this, but instead of --time-unit can shorter options be preferred like `-t`? Long options are a hell of a lot of work, and I don't understand why some CLI programs insist on preferring long options before all of the short alternatives have been exhausted.

**Comment by sharkdp** [comment]
I'm okay with a short option. I just suggested `-u` (for "unit", there are no other units in hyperfine) instead of `-t`.

> Long options are a hell of a lot of work, and I don't understand why some CLI programs insist on preferring long options before all of the short alternatives have been exhausted.

I typically add long command-line options to my programs because they have a self-documenting property which is great for usage in scripts.

Short options are great for interactive use of often-used features, but I tend to also be hesitant when adding new short flags because the namespace is really small and there might be better uses for a flag in the future. For rarely-used features (like hyperfines `--export-* <FILE>` flags), I think its perfectly fine to not have a short option because nobody will remember them anyway.

**Comment by jasonpeacock** [comment]
working on this now, will use the suggested `-u --time-unit <millisecond|second|...>` options

**Comment by sharkdp** [comment]
Released in [v1.4.0](https://github.com/sharkdp/hyperfine/releases/tag/v1.4.0).
