### ISSUE TITLE
Hyperfine only runs 1 benchmark, irrespective of --min-runs

### ISSUE THREAD

**Issue by Kaos-Industries** [sharkdp/hyperfine#88]
After 5GB and 2 hours' worth of dependency-chasing, I finally managed to install `hyperfine` via `cargo`. After then manually adding the `cargo` install folder to the Windows PATH environment variable, I'm finally able to run `hyperfine` in Cygwin.

However, when I do the following as a quick preliminary test:

`hyperfine -m 10 --show-output --export-csv hyperfinetest.csv 'sleep 1'`

I get the following output:

> Benchmark #1: sleep 1
>
> Time (mean ± σ):      1.036 s ±  0.006 s    [User: 4.1 ms, System: 17.4 ms]
>
> Range (min … max):    1.021 s …  1.040 s

I presume this means that only one benchmark was run, and checking hyperfinetest.csv seems to confirm this. What's going on here?

**Comment by sharkdp** [comment]
No. At least 10 runs (probably exactly 10) have been performed. It wouldn't be possible to show a standard deviation otherwise. `sleep 1` probably doesn't produce any output, so you won't see anything. Try `echo hello` instead (and use `--show-output`, as you did), if you want to make sure that hyperfine actually runs the command.

**Comment by sharkdp** [comment]
The CSV output shows only the aggregated results. If you run multiple benchmarks (`hyperfine "sleep 1" "sleep 2" "sleep 3"`), you would see more lines in the output.

**Comment by Kaos-Industries** [comment]
Ah, I see. So each benchmarks consists of a certain amount of runs, and the only way to run multiple benchmarks is to include more commands?

**Comment by sharkdp** [comment]
exactly
